name: step.image_one

on:
  workflow_call:
    inputs:
      job_name:
        type: string
        required: false
      dockerfile_name:
        type: string
        required: true
      build_args:
        type: string
        required: true
      image_name:
        type: string
        required: true
      image_tags:
        type: string
        required: true
    outputs:
      imageid:
        description: Image ID
        value: ${{ jobs.image.outputs.imageid }}
      digest:
        description: Image digest
        value: ${{ jobs.image.outputs.digest }}

jobs:
  image:
    name: ${{ inputs.job_name }}
    runs-on: ubuntu-latest
    outputs:
      imageid: ${{ steps.build.outputs.imageid }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.image_name }}
          tags: ${{ inputs.image_tags }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: src/${{ inputs.dockerfile_name }}
          context: src
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build_args }}
